server:
  port: 2222

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
springdoc:
  packagesToScan: com.runapp.shoesservice

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Run_App
    username: postgres
    password: 25032001
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
    hibernate:
      ddl-auto: create-drop
  application:
    name: shoes-service
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 6MB
  cloud:
    openfeign:
      client:
        config:
          storage-service:
            url: http://localhost:6500

storage-directory: ShoesService/



