server:
  port: ${SERVICE_SERVER_PORT:2222}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
springdoc:
  packagesToScan: com.runapp.shoesservice

eureka:
  client:
    enabled: false

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com
          issuer-uri: https://securetoken.google.com/runapp-407111
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql:///${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: ${SQL_INSTANCE_NAME}
        enableIamAuth: true
        sslmode: disable
      maximum-pool-size: 6
      minimum-idle: 5
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  application:
    name: shoes-service
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 6MB
  cloud:
    service-registry:
      auto-registration:
        enabled: false
    openfeign:
      client:
        config:
          storage-service:
            url: ${STORAGE_SERVICE_URL}
          profile-service:
            url: ${PROFILE_SERVICE_URL}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

storage-directory: ShoesService/